services:
  - type: web
    name: zyra-web
    env: python
    region: oregon
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn -w 2 -k uvicorn.workers.UvicornWorker --timeout 120 --keep-alive 5 --max-requests 1000 --max-requests-jitter 50 --bind 0.0.0.0:$PORT config.asgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_hqrO7D5glaKj@ep-round-smoke-ael2llxu-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
      - key: CLOUDINARY_URL
        value: "cloudinary://549768947857682:R2dzLnaTB_gIbCVcWF9ptUIVZN8@dg04dd5o1"
