# Generated by Django 5.2.4 on 2026-08-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="display_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("he/him", "Boy (he/him)"),
                    ("she/her", "Girl (she/her)"),
                    ("they/them", "They (they/them)"),
                    ("none", "Prefer not to say"),
                ],
                default="he/him",
                max_length=30,
            ),
        ),
    ]
