# Generated by Django 5.2.4 on 2026-08-28 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_userprofile_last_seen"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="story",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["user", "-created_at"], name="core_bookma_user_id_a7bdee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["post", "created_at"], name="core_commen_post_id_0d7c44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["-updated_at"], name="core_conver_updated_249e23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationparticipant",
            index=models.Index(
                fields=["user", "hidden_at"], name="core_conver_user_id_4bc7c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationparticipant",
            index=models.Index(
                fields=["conversation", "user"], name="core_conver_convers_7d331b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(
                fields=["follower", "following"], name="core_follow_followe_26835a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(
                fields=["following", "follower"], name="core_follow_followi_d6d1c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(
                fields=["user", "post"], name="core_like_user_id_244b74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(
                fields=["post", "created_at"], name="core_like_post_id_dda59d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "is_deleted", "-created_at"],
                name="core_messag_convers_45399a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagereaction",
            index=models.Index(
                fields=["message", "user"], name="core_messag_message_e711f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["receiver", "is_read", "-created_at"],
                name="core_notifi_receive_5aebf6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["receiver", "-created_at"],
                name="core_notifi_receive_094d77_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-created_at"], name="core_post_created_84f629_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["user", "-created_at"], name="core_post_user_id_5973f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["-created_at"], name="core_story_created_f3a776_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["user", "-created_at"], name="core_story_user_id_52e4c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["last_seen"], name="core_userpr_last_se_3827e8_idx"
            ),
        ),
    ]
