# Generated by Django 5.2.17 on 2026-08-29 19:22

import core.utils.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_conversation_updated_at_alter_post_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="voice_note",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=core.utils.media.UploadPath("voice_notes"),
            ),
        ),
    ]
