# Generated by Django 5.2.17 on 2026-08-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_message_voice_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="custom_theme_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="conversation_themes/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="theme_key",
            field=models.CharField(default="default", max_length=50),
        ),
    ]
