# Generated by Django 5.2.17 on 2026-08-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_conversation_custom_theme_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersistentMediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(db_index=True, max_length=500, unique=True),
                ),
                (
                    "content_type",
                    models.CharField(
                        default="application/octet-stream", max_length=100
                    ),
                ),
                ("data", models.BinaryField()),
                ("size", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["file_path"], name="core_persis_file_pa_40fa71_idx"
                    )
                ],
            },
        ),
    ]
