# Generated by Django 6.1 on 2026-08-30 08:30

import core.utils.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_persistentmediafile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="custom_theme_image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="conversation_themes/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=core.utils.media.UploadPath("direct"),
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="voice_note",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=core.utils.media.UploadPath("voice_notes"),
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=core.utils.media.UploadPath("posts"),
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="video",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=core.utils.media.UploadPath("reels"),
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=core.utils.media.UploadPath("stories"),
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="music",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=core.utils.media.UploadPath("stories"),
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="video",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=core.utils.media.UploadPath("stories"),
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=core.utils.media.UploadPath("avatars"),
            ),
        ),
    ]
